### ISSUE TITLE
Unable to visit start page... //  Incognito context could not be created!

### ISSUE THREAD

**Issue by drigga1512** [timbru31/mms-stockshock#385]
**Describe the bug**
error log shows two errors:
1) Unable to visit start page...
2) Incognito context could not be created!

**To Reproduce**
1. npm start
2. See error

**Expected behavior**
Do Login and start checking wishlist

**Screenshots**
No Screenshots

**Desktop (please complete the following information):**
- OS: Windows 10
- Version:	10.0.19043 Build 19043
- Node.js version: v16.13.0
**Additional context**
All sha256 keys and login-data have been filled and is correct

**Comment by timbru31** [comment]
Hi there,

I've pushed one change that could address the issue.
Generally, those errors come from Chromium itself and there is little I can do. Maybe your IP is wasted or currently on cooldown by CloudFlare, maybe MediaMarkt had issues with their backend - all those are wild guesses as without more and detailed information I can't tell where the error occurred and wyh.

Besides that, reF5resh decided that we won't work together. Sad, but unless this decision is changed, I'm not interested in giving user support. (which is in general not given for this project due to the sheer amount of time I'd spent answering questions)

Last note: Please keep in mind that the software is licensed under the GPL-3 license, i.e., [all changes, fixes or additions need to be disclosed.](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))

**Comment by drigga1512** [comment]
Don't worry I'm not a user, just wanted to inform you about that issue.
I won't use your project anyway.
